#!/usr/bin/env python3
"""Create a standalone project from the bundled multiomics template."""

from __future__ import annotations

import argparse
import csv
import json
import shutil
import sys
from pathlib import Path

from _common import SAMPLE_COLUMNS, WorkflowError, load_structured, write_json


SKILL_ROOT = Path(__file__).resolve().parents[1]
TEMPLATE = SKILL_ROOT / "assets" / "project-template"
RUNTIME_TOOLS = (
    "_common.py", "validate_project.py", "plan_workflow.py", "inspect_resources.py",
    "submit_workflow.py", "inspect_run.py", "update_report.py",
)

DEFAULT_ANALYSIS = {
    "scanpy": {
        "qc": {"min_genes": 200, "max_genes": 6000, "min_counts": 500, "max_mt_percent": 10.0, "min_cells_per_gene": 3},
        "scrublet": {"enabled": True, "min_cells": 100}, "target_sum": 10000,
        "n_hvg": 2000, "pca_components": 50, "n_pcs": 30, "n_neighbors": 15,
        "leiden_resolution": 0.8, "integration": "harmony", "seed": 0,
    },
    "methscan": {
        "min_sites": 300000, "min_meth_percent": 50, "max_meth_percent": 100,
        "smooth_bandwidth": 1000, "scan_bandwidth": 2000, "scan_stepsize": 100,
        "vmr_thresholds": [0.01, 0.02, 0.05], "min_cells": 6,
        "dmr": {"raw_p": 0.01, "min_abs_diff": 0.25, "top_per_cell_type": 200},
    },
    "allcools": {"bin_size": 5000, "mc_context": "CGN", "blacklist_fraction": 0.2},
    "methylvi": {
        "feature_targets": [10000, 30000], "epochs": 500, "batch_size": 32,
        "seed": 0, "validation_fraction": 0.1,
        "supervised_umap_weights": [0.2, 0.5, 0.7, 0.9],
    },
    "task_commands": {
        "scanpy": ["{python}", "{project}/Scripts/Scanpy/run_scanpy_project.py", "--project", "{project}", "--output-dir", "{task_dir}"]
    },
}

DEFAULT_PROFILES = {
    "default": {"floor": {"cpus": 1, "memory": "4G"}, "target": {"cpus": 4, "memory": "16G", "time": "1-00:00:00"}, "ceiling": {"cpus": 16, "memory": "64G"}},
    "serial": {"floor": {"cpus": 1, "memory": "8G"}, "target": {"cpus": 4, "memory": "16G", "time": "2-00:00:00"}, "ceiling": {"cpus": 8, "memory": "32G"}},
    "scanpy": {"floor": {"cpus": 4, "memory": "16G"}, "target": {"cpus": 16, "memory": "64G", "time": "2-00:00:00"}, "ceiling": {"cpus": 32, "memory": "128G"}},
    "io_builder": {"floor": {"cpus": 4, "memory": "16G"}, "target": {"cpus": 24, "memory": "64G", "time": "5-00:00:00"}, "ceiling": {"cpus": 56, "memory": "256G"}},
    "methscan_branch": {"floor": {"cpus": 4, "memory": "32G"}, "target": {"cpus": 18, "memory": "80G", "time": "2-00:00:00"}, "ceiling": {"cpus": 32, "memory": "160G"}},
    "dmr": {"floor": {"cpus": 4, "memory": "16G"}, "target": {"cpus": 8, "memory": "32G", "time": "5-00:00:00"}, "ceiling": {"cpus": 32, "memory": "96G"}},
    "dmr_prepare": {"floor": {"cpus": 2, "memory": "16G"}, "target": {"cpus": 8, "memory": "32G", "time": "1-00:00:00"}, "ceiling": {"cpus": 16, "memory": "64G"}},
    "feature_builder": {"floor": {"cpus": 8, "memory": "32G"}, "target": {"cpus": 32, "memory": "90G", "time": "7-00:00:00"}, "ceiling": {"cpus": 64, "memory": "256G"}},
    "trainer": {"floor": {"cpus": 8, "memory": "32G"}, "target": {"cpus": 32, "memory": "90G", "time": "7-00:00:00"}, "ceiling": {"cpus": 64, "memory": "256G"}},
    "plot": {"floor": {"cpus": 2, "memory": "8G"}, "target": {"cpus": 8, "memory": "32G", "time": "1-00:00:00"}, "ceiling": {"cpus": 16, "memory": "64G"}},
    "summary": {"floor": {"cpus": 1, "memory": "2G"}, "target": {"cpus": 2, "memory": "8G", "time": "02:00:00"}, "ceiling": {"cpus": 4, "memory": "16G"}},
}


def merge(base, override):
    result = json.loads(json.dumps(base))
    for key, value in (override or {}).items():
        if isinstance(value, dict) and isinstance(result.get(key), dict):
            result[key] = merge(result[key], value)
        else:
            result[key] = value
    return result


def bilingual_readme(project_id: str) -> str:
    return """# {0}

## 中文

本项目由 `single-cell-multiomics-analysis` 生成。所有路径、样本、参考基因组、环境和调度资源均由 `config/` 显式定义。运行前必须执行 `tools/validate_project.py`；正式任务只能通过 `tools/submit_workflow.py` 提交。

## English

This project was generated by `single-cell-multiomics-analysis`. Paths, samples, genome resources, environments, and scheduler resources are declared under `config/`. Run `tools/validate_project.py` before execution and submit production jobs only through `tools/submit_workflow.py`.
""".format(project_id)


def bilingual_report(project_id: str) -> str:
    return """# {0} analysis report / 分析报告

## Planned / 计划

- Status / 状态: initialized
- Runtime evidence is recorded under `.workflow/runs/`.
- 运行证据记录在 `.workflow/runs/`。

## Executed / 已执行

No production task has been submitted. / 尚未提交正式任务。
""".format(project_id)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--intake", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    intake = load_structured(args.intake)
    if intake.get("schema_version") != 1:
        raise WorkflowError("intake schema_version must be 1")
    output = args.output.resolve()
    if output.exists() and any(output.iterdir()):
        raise WorkflowError("refusing non-empty output directory: %s" % output)
    output.mkdir(parents=True, exist_ok=True)
    shutil.copytree(str(TEMPLATE), str(output), dirs_exist_ok=True)
    tools_dir = output / "tools"
    tools_dir.mkdir(exist_ok=True)
    for name in RUNTIME_TOOLS:
        shutil.copy2(str(SKILL_ROOT / "scripts" / name), str(tools_dir / name))

    project_id = str(intake.get("project_id", "")).strip()
    if not project_id:
        raise WorkflowError("project_id is required")
    references = intake.get("references") or {}
    project_cfg = {
        "schema_version": 1,
        "project": {
            "id": project_id, "root": str(output), "language": "zh-en",
            "organism": intake.get("organism", "unspecified"),
            "genome_id": references.get("genome_id", "unspecified"),
            "mitochondrial_prefixes": intake.get("mitochondrial_prefixes", ["MT-", "mt-"]),
        },
        "paths": {"results": "Results", "logs": "Scripts/logs", "state": ".workflow"},
        "references": references,
        "annotation": intake.get("annotation") or {"path": None, "cell_id_column": "cell_id", "cell_type_column": "cell_type"},
    }
    analysis_cfg = {"schema_version": 1, "analysis": merge(DEFAULT_ANALYSIS, intake.get("analysis") or {})}
    scheduler_cfg = merge({
        "schema_version": 1, "backend": "local", "account": None,
        "partitions": [], "allow_nodes": [], "exclude_nodes": [],
        "memory_headroom_mb": 4096, "max_parallel": 2,
        "local": {"max_threads": 16, "max_memory": "64G"}, "profiles": DEFAULT_PROFILES,
    }, intake.get("scheduler") or {})
    scheduler_cfg["schema_version"] = 1
    write_json(output / "config" / "project.yaml", project_cfg)
    write_json(output / "config" / "analysis.yaml", analysis_cfg)
    write_json(output / "config" / "scheduler.yaml", scheduler_cfg)

    samples = intake.get("samples") or []
    with (output / "config" / "samples.tsv").open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=SAMPLE_COLUMNS, delimiter="\t", lineterminator="\n")
        writer.writeheader()
        for sample in samples:
            writer.writerow({key: sample.get(key, "") for key in SAMPLE_COLUMNS})
    env_rows = intake.get("environments") or []
    env_columns = ("stage", "python", "executable", "version_command", "required")
    with (output / "config" / "environments.tsv").open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=env_columns, delimiter="\t", lineterminator="\n")
        writer.writeheader()
        for row in env_rows:
            writer.writerow({key: row.get(key, "") for key in env_columns})
    (output / "README.md").write_text(bilingual_readme(project_id), encoding="utf-8")
    (output / "Report.md").write_text(bilingual_report(project_id), encoding="utf-8")
    write_json(output / ".workflow" / "template-lock.json", {
        "skill": "single-cell-multiomics-analysis", "skill_version": (SKILL_ROOT / "VERSION").read_text().strip(),
        "schema_version": 1,
    })
    print(json.dumps({"project": str(output), "status": "initialized"}, indent=2))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (WorkflowError, OSError, ValueError) as exc:
        print("ERROR: %s" % exc, file=sys.stderr)
        raise SystemExit(2)
